# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Junfei Zhan (占俊飞)"   # 主页标题
description              : "MS Student in Electrical Engineering at the University of Pennsylvania"  # 主页描述
repository               : "junfei-z/junfei-z.github.io"  # USER_NAME/REPO_NAME
google_scholar_stats_use_cdn : false  # 切换为true可使用CDN，以防无法直接访问githubusercontent

# google analytics (可选)
google_analytics_id      :  # e.g., "UA-XXXXXXXXX-X"

# SEO 相关 (可选)
google_site_verification :  # get from https://search.google.com/search-console/about
bing_site_verification   :  # get from https://www.bing.com/webmasters/about
baidu_site_verification  :  # get from https://ziyuan.baidu.com/login

# Site Author
author:
  name             : "Junfei Z."
  avatar           : "images/android-chrome-512x512.png"
  bio              : "University of Pennsylvania, M.S.E. in Electrical Engineering"
  location         : "Philadelphia, PA, USA"
  employer         :
  pubmed           :
  googlescholar    : "https://scholar.google.com/citations?user=IFibJMkAAAAJ&hl=en"
  email            : "zjf2024@seas.upenn.edu"
  researchgate     :
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "Junfei-Z"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      :
  lastfm           :
  linkedin         : "https://www.linkedin.com/in/junfei-z/"
  dblp             :
  orcid            :
  pinterest        :
  soundcloud       :
  stackoverflow    :
  steam            :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :

# Reading Files
include:
  - .htaccess
  - _pages
  - files

exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# mimic GitHub Pages --safe mode
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

